name: japx_example
description: Demonstrates how to use the japx plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  japx:
    path: ../

  cupertino_icons: ^0.1.3
  json_serializable: ^3.2.5
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4


flutter:

  uses-material-design: true
  assets:
    - assets/
